{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}

  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: ecommerce-production-platform

spec:
  replicas: {{ $svc.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/part-of: ecommerce-production-platform

    spec:

      serviceAccountName: ecommerce-sa

      imagePullSecrets:
{{ toYaml $.Values.imagePullSecrets | nindent 8 }}


      containers:
        - name: {{ $name }}
          image: "{{ $svc.image }}:{{ $svc.tag }}"
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

            capabilities:
              drop:
                - ALL

          resources:
{{ toYaml $svc.resources | nindent 12 }}

          ports:
            - containerPort: {{ $svc.port }}

{{- if eq $name "redis-cart" }}

          volumeMounts:
            - name: redis-storage
              mountPath: /data

{{- end }}

          startupProbe:
            tcpSocket:
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: {{ $svc.port }}
            initialDelaySeconds: 15
            periodSeconds: 20

          envFrom:
            - configMapRef:
                name: {{ $name }}-config

          env:
{{- with $svc.env }}
{{ toYaml . | nindent 12 }}
{{- end }}

{{- if eq $name "redis-cart" }}

      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc

{{- end }}

{{- end }}

