{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: ecommerce-production-platform

spec:
  replicas: {{ $svc.replicas }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/part-of: ecommerce-production-platform

    spec:
      imagePullSecrets:
{{ toYaml $.Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: {{ $name }}
          image: "{{ $svc.image }}:{{ $svc.tag }}"
          imagePullPolicy: IfNotPresent

          resources:
{{ toYaml $svc.resources | nindent 12 }}

          ports:
            - containerPort: {{ $svc.port }}

          readinessProbe:
            tcpSocket:
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 10


{{- if $svc.env }}
          env:
{{ toYaml $svc.env | nindent 12 }}
{{- end }}

{{- end }}

