apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ecommerce-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"

  gateways:
    - ecommerce-gateway

  http:
    - retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: gateway-error,connect-failure,refused-stream,5xx

      timeout: 5s

      route:
        - destination:
            host: frontend
            subset: v1
            port:
              number: 8080
          weight: 90

        - destination:
            host: frontend
            subset: v2
            port:
              number: 8080
          weight: 10
