apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: checkoutservice
    app.kubernetes.io/part-of: ecommerce-production-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: grpc
      protocol: TCP
