imagePullSecrets:
  - name: ecr-registry-credentials
services:
  frontend:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/frontend
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 8080
    serviceType: NodePort
    nodePort: 30081
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "8080"
      - name: LISTEN_ADDR
        value: "0.0.0.0"
      - name: ENABLE_TRACING
        value: "1"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: COLLECTOR_SERVICE_ADDR
        value: "otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_ASSISTANT
        value: "false"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"
      - name: SHOPPING_ASSISTANT_SERVICE_ADDR
        value: "shoppingassistantservice:8080"
  currencyservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/currencyservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 7000
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "7000"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  productcatalogservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/productcatalogservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 3550
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "3550"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  recommendationservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/recommendationservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 8080
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  adservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/adservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 1
    port: 9555
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "9555"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  shippingservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/shippingservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 50051
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  paymentservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/paymentservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 50051
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "1"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
  checkoutservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/checkoutservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 5050
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "5050"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:8080"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "1"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: COLLECTOR_SERVICE_ADDR
        value: "otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
  emailservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/emailservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 8080
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: PORT
        value: "8080"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  cartservice:
    image: 324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/cartservice
    tag: 6d9a2c4daaa79c438be928514361252c137b8870
    replicas: 2
    port: 7070
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: REDIS_ADDR
        value: "redis-cart:6379"
      - name: PORT
        value: "7070"
      - name: DISABLE_PROFILER
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
      - name: ENABLE_TRACING
        value: "0"
  redis-cart:
    image: redis
    tag: "7.2-alpine"
    replicas: 1
    port: 6379
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      - name: REDIS_MODE
        value: "standalone"
ingress:
  enabled: true
  className: traefik
  host: ""
