services:

  productcatalogservice:
    image: ecommerce-productcatalog:dev
    environment:
      PORT: "3550"
      ENABLE_TRACING: "0"
      DISABLE_PROFILER: "1"

  currencyservice:
    image: ecommerce-currency:dev
    environment:
      PORT: "7000"
      DISABLE_PROFILER: "1"
      ENABLE_TRACING: "0"

  cartservice:
    image: ecommerce-cart:dev
    environment:
      ASPNETCORE_URLS: "http://+:7070"

  shippingservice:
    image: ecommerce-shipping:dev
    environment:
      PORT: "50051"
      DISABLE_TRACING: "1"
      DISABLE_PROFILER: "1"
      DISABLE_STATS: "1"

  emailservice:
    image: ecommerce-email:dev
    environment:
      PORT: "8080"
      DISABLE_PROFILER: "1"
      ENABLE_TRACING: "0"

  paymentservice:
    image: ecommerce-payment:dev
    environment:
      PORT: "50051"
      DISABLE_PROFILER: "1"
      ENABLE_TRACING: "0"

  adservice:
    image: ecommerce-ad:dev
    environment:
      PORT: "9555"
      DISABLE_STATS: "1"
      DISABLE_TRACING: "1"

  recommendationservice:
    image: ecommerce-recommendation:dev
    environment:
      PORT: "8080"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      DISABLE_PROFILER: "1"
      ENABLE_TRACING: "0"
    depends_on:
      - productcatalogservice

  checkoutservice:
    image: ecommerce-checkout:dev
    environment:
      PORT: "5050"
      ENABLE_TRACING: "0"
      ENABLE_PROFILER: "0"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      CART_SERVICE_ADDR: "cartservice:7070"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      EMAIL_SERVICE_ADDR: "emailservice:8080"
      PAYMENT_SERVICE_ADDR: "paymentservice:50051"
    depends_on:
      - shippingservice
      - productcatalogservice
      - cartservice
      - currencyservice
      - emailservice
      - paymentservice

  frontend:
    image: ecommerce-frontend:dev
    environment:
      PORT: "8080"
      LISTEN_ADDR: "0.0.0.0"
      ENABLE_TRACING: "0"
      ENABLE_PROFILER: "0"
      ENABLE_ASSISTANT: "false"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
      RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
      CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      AD_SERVICE_ADDR: "adservice:9555"
      SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:8080"
    ports:
      - "8081:8080"
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - recommendationservice
      - checkoutservice
      - shippingservice
      - adservice

