sonar.projectKey=ecommerce-production-platform
sonar.projectName=ecommerce-production-platform
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.host.url=http://40.192.39.25:31937
sonar.token=squ_b4c4f4990398a64dad65806b657b7a9128f4dcf5

sonar.exclusions=**/*.java
