apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: ecommerce-production-platform
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
