apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: disk-alert-rules
  namespace: monitoring
spec:
  groups:
    - name: disk.rules
      rules:
        - alert: HighDiskUsage
          expr: (100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)) > 85
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Disk Usage High"
            description: "Disk usage is above 85%."
