apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/part-of: ecommerce-production-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: grpc
      protocol: TCP
