alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: "smtp.gmail.com:587"
      smtp_from: "anilkumaruak93@gmail.com"
      smtp_auth_username: "anilkumaruak93@gmail.com"
      smtp_auth_password: "tjjz drwu xjwi pvql"
      smtp_require_tls: true

    route:
      receiver: gmail
      group_by:
        - alertname
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1m

    receivers:
      - name: gmail
        email_configs:
          - to: "anilkumaruak93@gmail.com"
            from: "anilkumaruak93@gmail.com"
            smarthost: "smtp.gmail.com:587"
            auth_username: "anilkumaruak93@gmail.com"
            auth_password: "tjjz drwu xjwi pvql"
            require_tls: true
            send_resolved: true
