apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    app.kubernetes.io/name: ecommerce-production-platform
    app.kubernetes.io/part-of: ecommerce-production-platform
    environment: dev
