apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ecommerce-istio
  namespace: istio-system
spec:
  profile: demo

  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 512Mi
