name: Microservices CI

on:
  push:
    branches:
      - feature

jobs:

  sonarqube:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: SonarQube Scan
        run: |
          cat > sonar-project.properties <<EOF
          sonar.projectKey=ecommerce-production-platform
          sonar.projectName=ecommerce-production-platform
          sonar.projectVersion=1.0
          sonar.sources=.
          sonar.sourceEncoding=UTF-8
          sonar.host.url=${{ secrets.SONAR_HOST_URL }}
          sonar.token=${{ secrets.SONAR_TOKEN }}
          sonar.exclusions=**/*.java
          EOF

          docker run --rm \
            -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli:latest


  build-and-push:
    needs: sonarqube

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        service:
          - frontend
          - cartservice
          - checkoutservice
          - currencyservice
          - productcatalogservice
          - recommendationservice
          - adservice
          - shippingservice
          - paymentservice
          - emailservice

    steps:

      - uses: actions/checkout@v4


      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t ecommerce/${{ matrix.service }}:${{ github.sha }} \
            ./src/${{ matrix.service }}

      - name: Tag Image
        run: |
          docker tag \
          ecommerce/${{ matrix.service }}:${{ github.sha }} \
          324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/${{ matrix.service }}:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          324352301255.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/${{ matrix.service }}:${{ github.sha }}


  update-values:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm Values
        run: |
          sed -i "s/tag: .*/tag: ${GITHUB_SHA}/g" helm/ecommerce/values.yaml

      - name: Commit Updated values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add helm/ecommerce/values.yaml

          git diff --cached --quiet || git commit -m "ci: update image tags to ${GITHUB_SHA}"

          git push


#  deploy:
#   needs: build-and-push
#    runs-on: self-hosted

#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Deploy Application
#        run: |
#          cd $GITHUB_WORKSPACE

#          helm upgrade --install ecommerce ./helm/ecommerce \
#            -n ecommerce-helm \
#            --set services.frontend.tag=${{ github.sha }} \
#            --set services.cartservice.tag=${{ github.sha }} \
#            --set services.checkoutservice.tag=${{ github.sha }} \
#            --set services.currencyservice.tag=${{ github.sha }} \
#            --set services.productcatalogservice.tag=${{ github.sha }} \
#            --set services.recommendationservice.tag=${{ github.sha }} \
#            --set services.adservice.tag=${{ github.sha }} \
#            --set services.shippingservice.tag=${{ github.sha }} \
#            --set services.paymentservice.tag=${{ github.sha }} \
#            --set services.emailservice.tag=${{ github.sha }}

#      - name: Wait for Frontend Rollout
#        run: |
#          kubectl rollout status deployment/frontend \
#            -n ecommerce-helm \
#            --timeout=15m
